// Generated by data/analysis/calibrate_model.py -- do not edit by hand.
// Constants measured from 394,453 Chicago 311 pothole requests (2011-2018),
// Open-Meteo ERA5 weather and Chicago ADT traffic counts.

export default {
  "generated": "2026-09-26",
  "provenance": {
    "potholes": "Chicago 311 'Pot Holes Reported' 2011-2018 (Socrata 7as2-ds3y), 395,236 requests after removing city-flagged duplicates",
    "weather": "Open-Meteo ERA5 daily reanalysis, Chicago 2011-2018",
    "traffic": "Chicago Average Daily Traffic Counts (Socrata pfsx-4n4m)"
  },
  "seasonality": {
    "report_index": {
      "Jan": 1.295,
      "Feb": 1.722,
      "Mar": 1.963,
      "Apr": 1.637,
      "May": 1.166,
      "Jun": 0.931,
      "Jul": 0.725,
      "Aug": 0.603,
      "Sep": 0.513,
      "Oct": 0.503,
      "Nov": 0.405,
      "Dec": 0.559
    },
    "peak_month": "Mar",
    "peak_trough_ratio": 4.846913580246913,
    "spring_share_mean": 0.4327002719834675,
    "spring_share_sd": 0.031050584225171405
  },
  "damage_driver": {
    "monthly_damage_index": {
      "Jan": 2.3838,
      "Feb": 2.5288,
      "Mar": 2.5237,
      "Apr": 0.8455,
      "May": 0.0,
      "Jun": 0.0,
      "Jul": 0.0,
      "Aug": 0.0,
      "Sep": 0.0,
      "Oct": 0.0146,
      "Nov": 1.3071,
      "Dec": 2.3964
    },
    "ft_days_per_year_mean": 58.125,
    "ft_days_per_year_min": 35,
    "ft_days_per_year_max": 96
  },
  "growth": {
    "form": "logistic",
    "severity_cap": 100.0,
    "k_per_damage_month": 0.20477251076892056,
    "k_fast": 0.6808685983066608,
    "k_slow": 0.10105656375609068,
    "anchor": {
      "from_severity": 40.0,
      "to_severity": 80.0,
      "over_months": 8.75,
      "basis": "median interval between repeat 311 reports on the same block"
    },
    "confidence": "low - no published growth rate exists for untreated potholes"
  },
  "repair": {
    "median_days_to_fill": 6.0,
    "p90_days_to_fill": 60.0,
    "median_by_month": {
      "Jan": 1.0,
      "Feb": 2.0,
      "Mar": 5.0,
      "Apr": 7.0,
      "May": 15.0,
      "Jun": 18.0,
      "Jul": 17.0,
      "Aug": 15.0,
      "Sep": 17.0,
      "Oct": 13.0,
      "Nov": 7.0,
      "Dec": 2.0
    },
    "holes_per_block_median": 7.0
  },
  "reopen": {
    "blocks": 189118,
    "repeat_share": 0.35984411848687065,
    "n_intervals": 182957,
    "days_between_reports": {
      "p10": 34.0,
      "p25": 80.0,
      "p50": 266.0,
      "p75": 539.0,
      "p90": 979.0
    },
    "median_days": 266.0
  },
  "excluded_predictors": {
    "traffic_volume": {
      "reason": "no usable signal in Chicago data",
      "incidence_r": 0.02812202988952012,
      "intensity_lift": 1.0,
      "caveat": "ADT counters sit only on arterials (p5 = 5,200 veh/day), so this tests arterial against arterial, never quiet against busy. The physical literature says traffic propagates damage; this data cannot resolve it, so it is left out rather than fitted to noise."
    },
    "year_ahead_freeze_thaw": {
      "reason": "freeze-thaw count does not rank winters by severity",
      "season_level_r": -0.3593506663149466,
      "n_seasons": 7,
      "caveat": "within-year shape is used; between-year prediction is not claimed."
    }
  }
}
