// Generated by data/analysis/calibrate_model.py -- do not edit by hand.
// Constants measured from 394,453 Chicago 311 pothole requests (2011-2018),
// Open-Meteo ERA5 weather and Chicago ADT traffic counts.

export default {
  "generated": "2026-09-26",
  "provenance": {
    "potholes": "Chicago 311 'Pot Holes Reported' 2011-2018 (Socrata 7as2-ds3y), 395,236 requests after removing city-flagged duplicates",
    "weather": "Open-Meteo ERA5 daily reanalysis, Chicago 2011-2018",
    "traffic": "Chicago Average Daily Traffic Counts (Socrata pfsx-4n4m)"
  },
  "seasonality": {
    "report_index": {
      "Jan": 1.295,
      "Feb": 1.722,
      "Mar": 1.963,
      "Apr": 1.637,
      "May": 1.166,
      "Jun": 0.931,
      "Jul": 0.725,
      "Aug": 0.603,
      "Sep": 0.513,
      "Oct": 0.503,
      "Nov": 0.405,
      "Dec": 0.559
    },
    "peak_month": "Mar",
    "peak_trough_ratio": 4.846913580246913,
    "spring_share_mean": 0.4327002719834675,
    "spring_share_sd": 0.031050584225171405
  },
  "damage_driver": {
    "monthly_damage_index": {
      "Jan": 2.3838,
      "Feb": 2.5288,
      "Mar": 2.5237,
      "Apr": 0.8455,
      "May": 0.0,
      "Jun": 0.0,
      "Jul": 0.0,
      "Aug": 0.0,
      "Sep": 0.0,
      "Oct": 0.0146,
      "Nov": 1.3071,
      "Dec": 2.3964
    },
    "ft_days_per_year_mean": 58.125,
    "ft_days_per_year_min": 35,
    "ft_days_per_year_max": 96
  },
  "climate": {
    "normal": {
      "Jan": {
        "ft_days": 10.9,
        "precip_mm": 53.3,
        "snow_cm": 15.2,
        "tmin_c": -7.4,
        "tmax_c": -0.7,
        "damage_index": 2.399
      },
      "Feb": {
        "ft_days": 11.1,
        "precip_mm": 66.2,
        "snow_cm": 24.6,
        "tmin_c": -7.2,
        "tmax_c": 0.0,
        "damage_index": 2.545
      },
      "Mar": {
        "ft_days": 13.0,
        "precip_mm": 64.4,
        "snow_cm": 10.0,
        "tmin_c": -1.6,
        "tmax_c": 4.8,
        "damage_index": 2.54
      },
      "Apr": {
        "ft_days": 3.8,
        "precip_mm": 111.3,
        "snow_cm": 3.3,
        "tmin_c": 3.7,
        "tmax_c": 10.5,
        "damage_index": 0.851
      },
      "May": {
        "ft_days": 0.0,
        "precip_mm": 119.8,
        "snow_cm": 0.0,
        "tmin_c": 10.8,
        "tmax_c": 17.9,
        "damage_index": 0.0
      },
      "Jun": {
        "ft_days": 0.0,
        "precip_mm": 107.7,
        "snow_cm": 0.0,
        "tmin_c": 16.6,
        "tmax_c": 23.7,
        "damage_index": 0.0
      },
      "Jul": {
        "ft_days": 0.0,
        "precip_mm": 102.2,
        "snow_cm": 0.0,
        "tmin_c": 20.1,
        "tmax_c": 26.3,
        "damage_index": 0.0
      },
      "Aug": {
        "ft_days": 0.0,
        "precip_mm": 99.8,
        "snow_cm": 0.0,
        "tmin_c": 19.4,
        "tmax_c": 25.6,
        "damage_index": 0.0
      },
      "Sep": {
        "ft_days": 0.0,
        "precip_mm": 68.7,
        "snow_cm": 0.0,
        "tmin_c": 16.1,
        "tmax_c": 22.1,
        "damage_index": 0.0
      },
      "Oct": {
        "ft_days": 0.1,
        "precip_mm": 103.9,
        "snow_cm": 0.1,
        "tmin_c": 9.6,
        "tmax_c": 15.5,
        "damage_index": 0.015
      },
      "Nov": {
        "ft_days": 6.9,
        "precip_mm": 67.4,
        "snow_cm": 6.6,
        "tmin_c": 2.2,
        "tmax_c": 7.7,
        "damage_index": 1.316
      },
      "Dec": {
        "ft_days": 12.4,
        "precip_mm": 63.5,
        "snow_cm": 11.7,
        "tmin_c": -2.7,
        "tmax_c": 2.6,
        "damage_index": 2.412
      }
    },
    "actual": {
      "2022-10": {
        "ft_days": 0,
        "precip_mm": 86.9,
        "snow_cm": 0.2,
        "tmin_c": 7.4,
        "tmax_c": 16.2,
        "damage_index": 0.0
      },
      "2022-11": {
        "ft_days": 11,
        "precip_mm": 38.6,
        "snow_cm": 4.4,
        "tmin_c": 1.8,
        "tmax_c": 10.0,
        "damage_index": 1.789
      },
      "2022-12": {
        "ft_days": 11,
        "precip_mm": 59.3,
        "snow_cm": 7.8,
        "tmin_c": -4.8,
        "tmax_c": 2.1,
        "damage_index": 2.168
      },
      "2023-01": {
        "ft_days": 16,
        "precip_mm": 64.9,
        "snow_cm": 15.8,
        "tmin_c": -3.3,
        "tmax_c": 3.0,
        "damage_index": 3.193
      },
      "2023-02": {
        "ft_days": 17,
        "precip_mm": 90.2,
        "snow_cm": 8.6,
        "tmin_c": -4.0,
        "tmax_c": 5.0,
        "damage_index": 2.94
      },
      "2023-03": {
        "ft_days": 14,
        "precip_mm": 84.8,
        "snow_cm": 17.4,
        "tmin_c": -0.9,
        "tmax_c": 6.6,
        "damage_index": 3.177
      },
      "2023-04": {
        "ft_days": 2,
        "precip_mm": 71.3,
        "snow_cm": 2.3,
        "tmin_c": 4.4,
        "tmax_c": 15.1,
        "damage_index": 0.243
      },
      "2023-05": {
        "ft_days": 0,
        "precip_mm": 47.1,
        "snow_cm": 0.0,
        "tmin_c": 9.4,
        "tmax_c": 19.0,
        "damage_index": 0.0
      },
      "2023-06": {
        "ft_days": 0,
        "precip_mm": 62.0,
        "snow_cm": 0.0,
        "tmin_c": 15.1,
        "tmax_c": 24.3,
        "damage_index": 0.0
      },
      "2023-07": {
        "ft_days": 0,
        "precip_mm": 308.5,
        "snow_cm": 0.0,
        "tmin_c": 18.4,
        "tmax_c": 26.5,
        "damage_index": 0.0
      },
      "2023-08": {
        "ft_days": 0,
        "precip_mm": 111.9,
        "snow_cm": 0.0,
        "tmin_c": 18.3,
        "tmax_c": 25.8,
        "damage_index": 0.0
      },
      "2023-09": {
        "ft_days": 0,
        "precip_mm": 170.0,
        "snow_cm": 0.0,
        "tmin_c": 16.0,
        "tmax_c": 22.9,
        "damage_index": 0.0
      },
      "2023-10": {
        "ft_days": 2,
        "precip_mm": 126.2,
        "snow_cm": 0.9,
        "tmin_c": 9.2,
        "tmax_c": 16.3,
        "damage_index": 0.454
      },
      "2023-11": {
        "ft_days": 8,
        "precip_mm": 35.0,
        "snow_cm": 2.3,
        "tmin_c": 1.6,
        "tmax_c": 9.5,
        "damage_index": 1.198
      },
      "2023-12": {
        "ft_days": 15,
        "precip_mm": 73.5,
        "snow_cm": 2.5,
        "tmin_c": 0.5,
        "tmax_c": 6.3,
        "damage_index": 2.639
      },
      "2024-01": {
        "ft_days": 17,
        "precip_mm": 108.8,
        "snow_cm": 31.8,
        "tmin_c": -6.5,
        "tmax_c": -0.8,
        "damage_index": 4.404
      },
      "2024-02": {
        "ft_days": 18,
        "precip_mm": 16.6,
        "snow_cm": 4.3,
        "tmin_c": -1.7,
        "tmax_c": 7.7,
        "damage_index": 2.965
      },
      "2024-03": {
        "ft_days": 15,
        "precip_mm": 118.6,
        "snow_cm": 9.4,
        "tmin_c": 1.1,
        "tmax_c": 9.8,
        "damage_index": 2.639
      },
      "2024-04": {
        "ft_days": 1,
        "precip_mm": 109.7,
        "snow_cm": 3.9,
        "tmin_c": 6.0,
        "tmax_c": 14.7,
        "damage_index": 0.122
      },
      "2024-05": {
        "ft_days": 0,
        "precip_mm": 98.2,
        "snow_cm": 0.0,
        "tmin_c": 11.5,
        "tmax_c": 21.2,
        "damage_index": 0.0
      },
      "2024-06": {
        "ft_days": 0,
        "precip_mm": 72.7,
        "snow_cm": 0.0,
        "tmin_c": 17.9,
        "tmax_c": 27.4,
        "damage_index": 0.0
      },
      "2024-07": {
        "ft_days": 0,
        "precip_mm": 171.5,
        "snow_cm": 0.0,
        "tmin_c": 18.8,
        "tmax_c": 26.9,
        "damage_index": 0.0
      },
      "2024-08": {
        "ft_days": 0,
        "precip_mm": 70.1,
        "snow_cm": 0.0,
        "tmin_c": 18.7,
        "tmax_c": 27.4,
        "damage_index": 0.0
      },
      "2024-09": {
        "ft_days": 0,
        "precip_mm": 67.0,
        "snow_cm": 0.0,
        "tmin_c": 16.2,
        "tmax_c": 24.8,
        "damage_index": 0.0
      },
      "2024-10": {
        "ft_days": 0,
        "precip_mm": 53.8,
        "snow_cm": 0.2,
        "tmin_c": 9.7,
        "tmax_c": 19.6,
        "damage_index": 0.0
      },
      "2024-11": {
        "ft_days": 3,
        "precip_mm": 95.0,
        "snow_cm": 5.7,
        "tmin_c": 5.0,
        "tmax_c": 10.7,
        "damage_index": 0.591
      },
      "2024-12": {
        "ft_days": 10,
        "precip_mm": 48.8,
        "snow_cm": 4.3,
        "tmin_c": -3.1,
        "tmax_c": 2.9,
        "damage_index": 2.706
      },
      "2025-01": {
        "ft_days": 9,
        "precip_mm": 60.3,
        "snow_cm": 9.3,
        "tmin_c": -8.9,
        "tmax_c": -1.8,
        "damage_index": 1.933
      },
      "2025-02": {
        "ft_days": 7,
        "precip_mm": 23.7,
        "snow_cm": 12.0,
        "tmin_c": -6.5,
        "tmax_c": 0.4,
        "damage_index": 1.638
      },
      "2025-03": {
        "ft_days": 10,
        "precip_mm": 94.1,
        "snow_cm": 11.9,
        "tmin_c": 1.6,
        "tmax_c": 11.0,
        "damage_index": 2.051
      },
      "2025-04": {
        "ft_days": 2,
        "precip_mm": 64.7,
        "snow_cm": 0.2,
        "tmin_c": 5.5,
        "tmax_c": 14.1,
        "damage_index": 0.469
      },
      "2025-05": {
        "ft_days": 0,
        "precip_mm": 71.3,
        "snow_cm": 0.0,
        "tmin_c": 9.4,
        "tmax_c": 17.4,
        "damage_index": 0.0
      },
      "2025-06": {
        "ft_days": 0,
        "precip_mm": 124.0,
        "snow_cm": 0.0,
        "tmin_c": 17.7,
        "tmax_c": 27.0,
        "damage_index": 0.0
      },
      "2025-07": {
        "ft_days": 0,
        "precip_mm": 102.5,
        "snow_cm": 0.0,
        "tmin_c": 21.0,
        "tmax_c": 28.6,
        "damage_index": 0.0
      },
      "2025-08": {
        "ft_days": 0,
        "precip_mm": 42.5,
        "snow_cm": 0.0,
        "tmin_c": 19.3,
        "tmax_c": 26.2,
        "damage_index": 0.0
      },
      "2025-09": {
        "ft_days": 0,
        "precip_mm": 38.5,
        "snow_cm": 0.0,
        "tmin_c": 16.1,
        "tmax_c": 23.9,
        "damage_index": 0.0
      },
      "2025-10": {
        "ft_days": 0,
        "precip_mm": 56.3,
        "snow_cm": 0.0,
        "tmin_c": 11.0,
        "tmax_c": 17.8,
        "damage_index": 0.0
      },
      "2025-11": {
        "ft_days": 6,
        "precip_mm": 73.7,
        "snow_cm": 22.5,
        "tmin_c": 2.6,
        "tmax_c": 9.1,
        "damage_index": 1.633
      },
      "2025-12": {
        "ft_days": 9,
        "precip_mm": 80.7,
        "snow_cm": 16.6,
        "tmin_c": -6.2,
        "tmax_c": 0.7,
        "damage_index": 2.37
      },
      "2026-01": {
        "ft_days": 6,
        "precip_mm": 50.9,
        "snow_cm": 18.8,
        "tmin_c": -9.2,
        "tmax_c": -2.1,
        "damage_index": 1.58
      },
      "2026-02": {
        "ft_days": 12,
        "precip_mm": 16.6,
        "snow_cm": 4.7,
        "tmin_c": -3.6,
        "tmax_c": 4.3,
        "damage_index": 2.289
      },
      "2026-03": {
        "ft_days": 11,
        "precip_mm": 94.8,
        "snow_cm": 5.2,
        "tmin_c": 0.9,
        "tmax_c": 11.0,
        "damage_index": 2.387
      },
      "2026-04": {
        "ft_days": 1,
        "precip_mm": 163.7,
        "snow_cm": 1.2,
        "tmin_c": 6.9,
        "tmax_c": 16.4,
        "damage_index": 0.122
      },
      "2026-05": {
        "ft_days": 0,
        "precip_mm": 33.6,
        "snow_cm": 0.0,
        "tmin_c": 11.0,
        "tmax_c": 19.7,
        "damage_index": 0.0
      },
      "2026-06": {
        "ft_days": 0,
        "precip_mm": 181.7,
        "snow_cm": 0.0,
        "tmin_c": 17.3,
        "tmax_c": 24.6,
        "damage_index": 0.0
      },
      "2026-07": {
        "ft_days": 0,
        "precip_mm": 106.0,
        "snow_cm": 0.0,
        "tmin_c": 20.8,
        "tmax_c": 28.0,
        "damage_index": 0.0
      },
      "2026-08": {
        "ft_days": 0,
        "precip_mm": 233.9,
        "snow_cm": 0.0,
        "tmin_c": 19.7,
        "tmax_c": 26.3,
        "damage_index": 0.0
      }
    }
  },
  "growth": {
    "form": "logistic",
    "severity_cap": 100.0,
    "k_per_damage_month": 0.20477251076892056,
    "k_fast": 0.6808685983066608,
    "k_slow": 0.10105656375609068,
    "anchor": {
      "from_severity": 40.0,
      "to_severity": 80.0,
      "over_months": 8.75,
      "basis": "median interval between repeat 311 reports on the same block"
    },
    "anchor_sensitivity": {
      "alternatives": [
        {
          "from": 40.0,
          "to": 80.0,
          "k": 0.20477251076892056,
          "label": "an existing hole 40 -> 80 (used)"
        },
        {
          "from": 10.0,
          "to": 45.0,
          "k": 0.22817758649989353,
          "label": "fresh patch 10 -> reportable 45"
        },
        {
          "from": 5.0,
          "to": 40.0,
          "k": 0.2901684424066601,
          "label": "fresh patch 5 -> reportable 40"
        },
        {
          "from": 25.0,
          "to": 70.0,
          "k": 0.22238973132060724,
          "label": "detectable 25 -> severe 70"
        }
      ],
      "span_choice_ratio": 1.4170282979735802,
      "population_spread_ratio": 6.737499999999999
    },
    "rate_population": {
      "interval_log_mu": 5.583496308781699,
      "interval_log_sigma": 1.3625393086385236,
      "logit_span": 1.791759469228055,
      "days_per_month": 30.4
    },
    "confidence": "low - no published growth rate exists for untreated potholes"
  },
  "repair": {
    "median_days_to_fill": 6.0,
    "p90_days_to_fill": 60.0,
    "median_by_month": {
      "Jan": 1.0,
      "Feb": 2.0,
      "Mar": 5.0,
      "Apr": 7.0,
      "May": 15.0,
      "Jun": 18.0,
      "Jul": 17.0,
      "Aug": 15.0,
      "Sep": 17.0,
      "Oct": 13.0,
      "Nov": 7.0,
      "Dec": 2.0
    },
    "holes_per_block_median": 7.0
  },
  "reopen": {
    "blocks": 189118,
    "repeat_share": 0.35984411848687065,
    "n_intervals": 182957,
    "days_between_reports": {
      "p10": 34.0,
      "p25": 80.0,
      "p50": 266.0,
      "p75": 539.0,
      "p90": 979.0
    },
    "median_days": 266.0
  },
  "excluded_predictors": {
    "traffic_volume": {
      "reason": "no usable signal in Chicago data",
      "incidence_r": 0.02812202988952012,
      "intensity_lift": 1.0,
      "caveat": "ADT counters sit only on arterials (p5 = 5,200 veh/day), so this tests arterial against arterial, never quiet against busy. The physical literature says traffic propagates damage; this data cannot resolve it, so it is left out rather than fitted to noise."
    },
    "year_ahead_freeze_thaw": {
      "reason": "freeze-thaw count does not rank winters by severity",
      "season_level_r": -0.3593506663149466,
      "n_seasons": 7,
      "caveat": "within-year shape is used; between-year prediction is not claimed."
    }
  }
}
